#!/bin/sh

# auto ssh to arukas docker vps via peeretc info(dynamic login host:port)
# usage: for ssh: akssh [extra ssh args]
# usage: for scp: akssh <srcfile> <dstfile> [extra scp args]

# 141-148-179
ipsfx=140
while true; do
    endpoint=""
    ipsfx=$(($ipsfx + 1))
    if [[ $ipsfx == "180" ]]; then
        break;
    fi
    ipfull="163.43.82.$ipsfx"
    epurl="http://localhost:5080/pcapi/endpoint?ip=$ipfull&port=22"
    echo "Get endpoint $epurl ..."
    endpoint=$(curl "$epurl")
    if [[ $endpoint == "" ]]; then
        #echo "Cannot get endpoint for $epurl"
        continue;
    fi
    host=$(echo $endpoint|awk -F: '{print $1}')
    port=$(echo $endpoint|awk -F: '{print $2}')
    nc -w 5 "$host" "$port"
    ret=$?
    if [[ $ret == 1 ]]; then
        continue;
    fi

    break;
done

if [[ $endpoint == "" ]]; then
    echo "Cannot get endpoint"
    exit -1;
fi
host=$(echo $endpoint|awk -F: '{print $1}')
port=$(echo $endpoint|awk -F: '{print $2}')

echo "host=$host port=$port"
sshcmd="ssh -C -p$port $@ root@$host"
scpcmd="scp -C -P$port $3 $4 $5 $1 root@$host:$2"

if [[ "$1" != "" ]] && ([[ -f "$1" ]] || [[ -d "$1" ]]) ; then
    echo "scpcmd $scpcmd"
    $scpcmd
else
    echo "sshcmd $sshcmd"
    $sshcmd
fi

ret=$?
echo "ret=$ret"

