#!/bin/sh
#exec xterm -u8 -geometry 120x40 -xrm XTerm*selectToClipboard:true -bg black -fg green -sh 1.2
exec xterm -u8 -geometry 120x50 -xrm XTerm*selectToClipboard:true -bg black -fg green3 -bdc -pc -fbb -font '*-fixed-*-*-*-18-*' "$@"

# todo font size not work
# exec xterm -u8 -geometry 120x50 -xrm XTerm*selectToClipboard:true -bg black -fg green4 -bdc -pc -fbb -fn 18 -fa 'Source Code Pro:style=Bold' "$@"

# https://critical.ch/xterm/
