#!/bin/sh

# set -x
SELF=$(readlink -f $0)
#echo "$SELF"

# fix second account
SSHIDENT=
if [[ "$2" =~ ^git-.+\ \'/?kitech/.+\.git\'$ && "$1" =~ ^git@github.com$ ]]; then
    # echo "got the second account: kitech"
    SSHIDENT="-i $HOME/.ssh/id_rsa_github"
fi
if [[ "$2" =~ ^git-.+\ \'/?aitjcize/.+\.git\'$ && "$1" =~ ^git@github.com$ ]]; then
    # echo "got the second account: kitech"
    SSHIDENT="-i $HOME/.ssh/id_rsa_github"
fi


#ssh -o ProxyCommand="/path/to/socks5proxywrapper %h %p" "$@"
if [ -d "$HOME/triline/myscripts-svn" ]; then
    ssh $SSHIDENT -o ProxyCommand="$HOME/triline/myscripts-svn/socks5proxywrapper %h %p" "$@"
else
    ssh $SSHIDENT -o ProxyCommand="$HOME/triline/myscripts/socks5proxywrapper %h %p" "$@"
fi

# 用法
# export GIT_SSH="/path/to/socks5proxyssh“

#
#GIT_SSH=$HOME/myscripts/socks5proxyssh GIT_TRACE=0 GIT_CURL_VERBOSE=1

